### ISSUE TITLE
{{errorLoginMessage}}

### ISSUE THREAD

**Issue by exlmath** [widestage/widestage#11]
hi,

I want test widestage on CentOS 7 64bits.

but when I go on the portal "http://IP/login" I have this message under login/password :
{{errorLoginMessage}}

I'm not an expert in linux... I don't find solution...

any idea?

thx a lot

**Comment by beevou** [comment]
At a first sight seems that all dependencies are not there, did you make the bower install?

**Comment by kimoudev** [comment]
I have a same error after bower install `widestage/node_modules/mongoose/node_modules/bson/ext/index.js:15:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
js-bson: Failed to load c++ bson extension, using pure JS version
{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
` i can't login
