### ISSUE TITLE
Unable to save - Save Initialisation parameters

### ISSUE THREAD

**Issue by RiaanBez** [widestage/widestage#114]
I get this error

[root@localhost wst_os_test]# node server.js
Loaded enviroment production
forking  0
Loaded enviroment production
/wst_os_test/server/serverConfig/../data/production/wiceServerConfig.yml
There is no configuration, the server must be configured first...
the port is 8089
Server running at http://10.0.3.18:8089/ in worker 1
 installed modules are :
the path to be saved is /wst_os_test/server/data/production
my configuration is : [object Object]
the global configuration is : [object Object]
the server/replset/mongos/db options are deprecated, all their options are supported at the top level of the options object [poolSize,ssl,sslValidate,sslCA,sslCert,sslKey,sslPass,sslCRL,autoReconnect,noDelay,keepAlive,keepAliveInitialDelay,connectTimeoutMS,family,socketTimeoutMS,reconnectTries,reconnectInterval,ha,haInterval,replicaSet,secondaryAcceptableLatencyMS,acceptableLatencyMS,connectWithNoPrimary,authSource,w,wtimeout,j,forceServerObjectId,serializeFunctions,ignoreUndefined,raw,bufferMaxEntries,readPreference,pkFactory,promiseLibrary,readConcern,maxStalenessSeconds,loggerLevel,logger,promoteValues,promoteBuffers,promoteLongs,domainsEnabled,checkServerIdentity,validateOptions,appname,auth,user,password,authMechanism,compression,fsync,readPreferenceTags,numberOfRetries,auto_reconnect,minSize,monitorCommands,retryWrites,retryReads,useNewUrlParser,useUnifiedTopology,serverSelectionTimeoutMS,useRecoveryToken,autoEncryption,driverInfo,tls,tlsInsecure,tlsinsecure,tlsAllowInvalidCertificates,tlsAllowInvalidHostnames,tlsCAFile,tlsCertificateFile,tlsCertificateKeyFile,tlsCertificateKeyFilePassword,minHeartbeatFrequencyMS,heartbeatFrequencyMS,directConnection,appName,maxPoolSize,minPoolSize,maxIdleTimeMS,waitQueueTimeoutMS]
(node:3555) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:3555) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
**Mongoose connection open to mongodb://localhost:27017/widestage
Error creating email template New User with password**
the path to be saved is /wst_os_test/server

**Comment by RiaanBez** [comment]
The file seem to have the saved in formation but when I  restart server.js i get the folowing error


[root@localhost wst_os_test]# node server.js
Loaded enviroment production
forking  0
Loaded enviroment production
/wst_os_test/server/serverConfig/../data/production/wiceServerConfig.yml
Applying stored server configuration...
the server/replset/mongos/db options are deprecated, all their options are supported at the top level of the options object [poolSize,ssl,sslValidate,sslCA,sslCert,sslKey,sslPass,sslCRL,autoReconnect,noDelay,keepAlive,keepAliveInitialDelay,connectTimeoutMS,family,socketTimeoutMS,reconnectTries,reconnectInterval,ha,haInterval,replicaSet,secondaryAcceptableLatencyMS,acceptableLatencyMS,connectWithNoPrimary,authSource,w,wtimeout,j,forceServerObjectId,serializeFunctions,ignoreUndefined,raw,bufferMaxEntries,readPreference,pkFactory,promiseLibrary,readConcern,maxStalenessSeconds,loggerLevel,logger,promoteValues,promoteBuffers,promoteLongs,domainsEnabled,checkServerIdentity,validateOptions,appname,auth,user,password,authMechanism,compression,fsync,readPreferenceTags,numberOfRetries,auto_reconnect,minSize,monitorCommands,retryWrites,retryReads,useNewUrlParser,useUnifiedTopology,serverSelectionTimeoutMS,useRecoveryToken,autoEncryption,driverInfo,tls,tlsInsecure,tlsinsecure,tlsAllowInvalidCertificates,tlsAllowInvalidHostnames,tlsCAFile,tlsCertificateFile,tlsCertificateKeyFile,tlsCertificateKeyFilePassword,minHeartbeatFrequencyMS,heartbeatFrequencyMS,directConnection,appName,maxPoolSize,minPoolSize,maxIdleTimeMS,waitQueueTimeoutMS]
Module companies admin loaded
users model loaded
Module auth loaded
Module admin email templates
Module roles admin loaded
Module users admin loaded
Module files loaded
Module help loaded
Module logs loaded
Module mailer loaded
Module notifications loaded
Module permissions loaded
Core permissions loaded
Module socket loaded
Module users loaded
Module Queue Message Broker V3 loaded
Module connections loaded
Module layers loaded
Module spaces loaded
Module wst-admin-users loaded
Module connection-drivers loaded
Module dashboards loaded
Module favourites loaded
Module wst-objects loaded
Module reports loaded
Module statistics loaded
the port is 8089
(node:2905) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:2905) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Server running at http://10.0.3.18:8089/ in worker 1
 installed modules are : companies
auth
adminEmailTemplates
roles admin
users admin
files
help
logs
mailer
notifications
permissions
socket
users
queueMessageBrokerV3
connections
layers
spaces
wst-admin-users
connection-drivers
dashboards
favourites
wst-objects
reports
statistics
Mongoose connection open to mongodb://localhost:27017/widestage
(node:2905) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
(node:2905) UnhandledPromiseRejectionWarning: MongoError: command createIndexes requires authentication
    at Connection.<anonymous> (/wst_os_test/node_modules/mongoose/node_modules/mongodb/lib/core/connection/pool.js:451:61)
    at Connection.emit (events.js:198:13)
    at processMessage (/wst_os_test/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connection.js:451:10)
    at Socket.<anonymous> (/wst_os_test/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connection.js:620:15)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
(node:2905) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2905) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code

**Comment by RiaanBez** [comment]
I manged to sort this out  - It was a momgo db config issiue
