### ISSUE TITLE
Error when trying to start the server

### ISSUE THREAD

**Issue by niros-tamos** [widestage/widestage#12]
Hi!
After starting the server on a fresh install in a VM Ubuntu box, I get this error, repeatedly:
----------------------------------------------------------------------------------------------------------------------------------
me@Ubuntu-HV:~/widestage$ node server.js

{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/me/widestage/node_modules/mongoose/node_modules/bson/ext/index.js:15:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
forking  0
----------------------------------------------------------------------------------------------------------------------------------
uname -a reads:
Linux Ubuntu-HV 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

node version is v6.9.1
bower version is 1.8.0
npm version is 3.10.8
MongoDB shell version: 2.6.10

Any idea on what must be wrong?

thanks,

Niros.

**Comment by niros-tamos** [comment]
SOLVED!
Edit the file:
./node_modules/mongoose/node_modules/bson/ext/index.js
And replace references to ../build/Release/bson by ../browser_build/bson

Also make sure to have provided proper IPs for the environment you're running (development, production or local) in ./server/config/config.js

Then you can start the server for the environment of your choice:
node server.js development
node server.js production 
-or-
node server.js local

nt.
