### ISSUE TITLE
error connecting to mssql

### ISSUE THREAD

**Issue by rizzopablo** [widestage/widestage#48]
Hi, whenever I try to connect to mssql databases, there is this error:

events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: Unknown type: 0
    at Parser.parseTokens (/home/pablor/Descargas/widestage/node_modules/tedious/lib/token/stream-parser.js:94:30)
    at Parser._transform (/home/pablor/Descargas/widestage/node_modules/tedious/lib/token/stream-parser.js:67:14)
    at Parser.Transform._read (/home/pablor/Descargas/widestage/node_modules/tedious/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at Parser.Transform._write (/home/pablor/Descargas/widestage/node_modules/tedious/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/home/pablor/Descargas/widestage/node_modules/tedious/node_modules/readable-stream/lib/_stream_writable.js:338:64)
    at writeOrBuffer (/home/pablor/Descargas/widestage/node_modules/tedious/node_modules/readable-stream/lib/_stream_writable.js:327:5)
    at Parser.Writable.write (/home/pablor/Descargas/widestage/node_modules/tedious/node_modules/readable-stream/lib/_stream_writable.js:264:11)
    at Parser.addBuffer (/home/pablor/Descargas/widestage/node_modules/tedious/lib/token/token-stream-parser.js:59:26)
    at Connection.sendDataToTokenStreamParser (/home/pablor/Descargas/widestage/node_modules/tedious/lib/connection.js:684:37)
    at Connection.data (/home/pablor/Descargas/widestage/node_modules/tedious/lib/connection.js:1108:21)
    at Connection.dispatchEvent (/home/pablor/Descargas/widestage/node_modules/tedious/lib/connection.js:559:45)
    at MessageIO.<anonymous> (/home/pablor/Descargas/widestage/node_modules/tedious/lib/connection.js:476:16)
    at emitOne (events.js:96:13)
    at MessageIO.emit (events.js:191:7)
    at ReadablePacketStream.<anonymous> (/home/pablor/Descargas/widestage/node_modules/tedious/lib/message-io.js:101:13)
    at emitOne (events.js:96:13)
worker 20526 died.
worker 20571 born.
mongo DB connection
Server running at http://0.0.0.0:8081/ in worker 11
Mongoose connection open to mongodb://localhost:27017/widestage

And connection fails. 
Also, there is no field to specify mssql db "instance".

**Comment by beevou** [comment]
<img width="1247" alt="screen shot 2017-06-01 at 10 19 35" src="https://cloud.githubusercontent.com/assets/2676312/26673227/0a46aab2-46b4-11e7-9338-8ea089ea0fc4.png">

I just check the MSSQL connection and seems to be working with no issues.
Please check your mssql npm package, if the problem persist, give a bit more context of the problem like where are you getting this error (data sources testing connection, executing a report, etc...)
